# https://docs.docker.com/compose/environment-variables/env-file/#interpolation

services:
  nginx:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    # https://www.paulsblog.dev/how-to-successfully-implement-a-healthcheck-in-docker-compose/
    healthcheck:
      test: "curl --fail -s http://127.0.0.1/health || exit 1"
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    ports:
      - 127.0.0.1:${WEB_PORT}:80
    extra_hosts:
      - host.docker.internal:host-gateway
